# Generated by Django 4.2.2 on 2023-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_details', '0002_user_email_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
